In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


3.1.1 task1

In [ ]:
import pandas as pd

data = pd.read_csv('/content/drive/MyDrive/Datasets/student.csv')

print("Top 5 rows of the dataset:")
print(data.head())

print("\nBottom 5 rows of the dataset:")
print(data.tail())

print("\nDataset Information:")
data.info()

print("\nDescriptive Statistics:")
print(data.describe())

X = data[['Math', 'Reading']]  # Features
Y = data['Writing']            # Label

print("\nFeatures (X):")
print(X.head())

print("\nLabel (Y):")
print(Y.head())


Top 5 rows of the dataset:
   Math  Reading  Writing
0    48       68       63
1    62       81       72
2    79       80       78
3    76       83       79
4    59       64       62

Bottom 5 rows of the dataset:
     Math  Reading  Writing
995    72       74       70
996    73       86       90
997    89       87       94
998    83       82       78
999    66       66       72

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Math     1000 non-null   int64
 1   Reading  1000 non-null   int64
 2   Writing  1000 non-null   int64
dtypes: int64(3)
memory usage: 23.6 KB

Descriptive Statistics:
              Math      Reading      Writing
count  1000.000000  1000.000000  1000.000000
mean     67.290000    69.872000    68.616000
std      15.085008    14.657027    15.241287
min      13.000000    19.000000    14.000000
25%      58.000000    

3.1.1 task2

In [ ]:
import numpy as np

# Define the dimensions
d = 3  # Number of features
n = 5  # Number of data points

# Step 1: Initialize feature matrix X (random values for illustration)
X = np.random.rand(d, n)  # X is a d x n matrix

# Step 2: Initialize weight vector W (random values for illustration)
W = np.random.rand(d, 1)  # W is a d x 1 matrix

# Step 3: Calculate the output Y = W^T X
Y = np.dot(W.T, X)  # Y will be a 1 x n matrix

# Step 4: Display the matrices
print("Feature Matrix (X):")
print(X)

print("\nWeight Vector (W):")
print(W)

print("\nOutput (Y = W^T X):")
print(Y)


Feature Matrix (X):
[[0.35118697 0.79532814 0.41645898 0.48526714 0.32097845]
 [0.37987407 0.29367421 0.79213139 0.01685208 0.04696211]
 [0.67088199 0.20029402 0.34757706 0.63700062 0.71063736]]

Weight Vector (W):
[[0.41482347]
 [0.00526458]
 [0.38844198]]

Output (Y = W^T X):
[[0.4082792  0.40926945 0.31194072 0.4488267  0.40943801]]


3.1.1 task3

In [ ]:
from sklearn.model_selection import train_test_split
import pandas as pd

data = pd.read_csv('/content/drive/MyDrive/Datasets/student.csv')

X = data[['Math', 'Reading']]  # Features
Y = data['Writing']           # Label

# Split the dataset into training and testing sets
# Using 80-20 split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Print the shapes of the splits
print("Training Features (X_train):")
print(X_train.shape)

print("\nTest Features (X_test):")
print(X_test.shape)

print("\nTraining Labels (Y_train):")
print(Y_train.shape)

print("\nTest Labels (Y_test):")
print(Y_test.shape)


Training Features (X_train):
(800, 2)

Test Features (X_test):
(200, 2)

Training Labels (Y_train):
(800,)

Test Labels (Y_test):
(200,)


3.1.5

In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

def load_and_split_data():
    # Placeholder: Replace with actual data loading
    data = np.random.rand(100, 5)  # Example data: 100 samples, 4 features + 1 target
    X = data[:, :-1]  # Features
    Y = data[:, -1]   # Target
    return train_test_split(X, Y, test_size=0.2, random_state=42)

def gradient_descent(X, Y, W, learning_rate, iterations):
    m = len(Y)
    for _ in range(iterations):
        predictions = X.dot(W)
        errors = predictions - Y
        gradient = (1 / m) * X.T.dot(errors)
        W -= learning_rate * gradient
    return W

def evaluate_model(X, Y, W):
    predictions = X.dot(W)
    rmse = np.sqrt(mean_squared_error(Y, predictions))
    r2 = r2_score(Y, predictions)
    return rmse, r2

def main():
    # Step 1: Load data and split into training and test sets
    X_train, X_test, Y_train, Y_test = load_and_split_data()

    # Step 2: Prepare feature matrix and target vector
    X_train = np.c_[np.ones(X_train.shape[0]), X_train]  # Add bias term
    X_test = np.c_[np.ones(X_test.shape[0]), X_test]     # Add bias term

    # Step 3: Initialize weights, learning rate, and iterations
    W = np.zeros(X_train.shape[1])
    learning_rate = 0.01
    iterations = 1000

    # Step 4: Perform gradient descent
    W = gradient_descent(X_train, Y_train, W, learning_rate, iterations)

    # Step 5: Evaluate the model
    rmse, r2 = evaluate_model(X_test, Y_test, W)
    print(f"RMSE: {rmse}")
    print(f"R2 Score: {r2}")

if __name__ == "__main__":
    main()


RMSE: 0.2866680065603583
R2 Score: -0.20421370666088356
